project_name: sams
builds:
  - main: ./cmd/app
    ldflags: -X github.com/Enriquefft/SAMS/pkg/version.Version={{.Version}} -X github.com/Enriquefft/SAMS/pkg/version.Commit={{.FullCommit}} -X github.com/Enriquefft/SAMS/pkg/version.BuildDate={{.Date}}
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Enriquefft
    name: SAMS
